# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo_pagador_pensiones', models.IntegerField(choices=[(1, 'Empleador'), (2, 'Administrador de pensiones'), (3, 'Pagador de pensiones'), (4, 'Pensiones de entidades de los reg\xedmenes especiales y de excepci\xf3n')])),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion', models.IntegerField()),
                ('tipo_novedad', models.IntegerField(choices=[(1, 'Traslado'), (2, 'Variaci\xf3n transitoria de salario'), (3, 'Supenci\xf3n temporal'), (4, 'Licencia no remunerada'), (5, 'Comisi\xf3n por servicios'), (6, 'Incapacidad temporal por enfermedad'), (7, 'Licencia maternidad/paternidad'), (8, 'Vacaciones'), (9, 'Licencia remunerada'), (10, 'Aporte volunatario a pensiones')])),
                ('aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.Aportante')),
            ],
        ),
        migrations.CreateModel(
            name='OperadorServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_salud', models.FloatField()),
                ('valor_pension', models.FloatField()),
                ('valor_riesgos', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.Aportante')),
            ],
        ),
        migrations.CreateModel(
            name='Pensionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('edad', models.IntegerField()),
                ('salario', models.FloatField()),
                ('es_alto_riesgo', models.BooleanField()),
                ('es_congresista', models.BooleanField()),
                ('es_trabajador_CTI', models.BooleanField()),
                ('es_aviador', models.BooleanField()),
                ('residencia_exterior', models.CharField(max_length=250)),
                ('tiene_grupo_familiar_colombia', models.BooleanField()),
                ('codigo_CIU', models.IntegerField()),
                ('tipo_pensionado', models.IntegerField(choices=[(1, 'Pensionado de r\xe9gimen de prima media. Tope m\xe1ximo de pensi\xf3n 25 smlmv'), (2, 'Pensionado de r\xe9gimen de prima media. Sin tope m\xe1ximo de pensi\xf3n'), (3, 'Pensionado de r\xe9gimen de ahorro individual. No aplica tope m\xe1ximo de pensi\xf3n'), (4, 'Pensionado de Riesgos Laborales. Tope m\xe1ximo de 25 smlmv'), (5, 'Pensionado por el empleador, con tope m\xe1ximo de pensi\xf3n 25 smlmv'), (6, 'Pensionado por el empleador sin tope m\xe1ximo de pensi\xf3n'), (7, 'Pensionado de entidades de los reg\xedmenes especial y de excepci\xf3n, con tope m\xe1ximo de pensi\xf3n 25 smlmv'), (8, 'Pensionado de entidades de los reg\xedmenes especial y de excepci\xf3n sin tope m\xe1ximo de pensi\xf3n'), (9, 'Beneficiario UPC adicional')])),
                ('aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.Aportante')),
            ],
        ),
        migrations.AddField(
            model_name='aportante',
            name='operador_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.OperadorServicio'),
        ),
        migrations.AddField(
            model_name='aportante',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
