# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='pensionado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pila.Pensionado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='pensionado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pila.Pensionado'),
            preserve_default=False,
        ),
    ]
