# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0002_auto_20161031_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='pensionado',
            new_name='beneficiario',
        ),
    ]
